site_name: Ractive.js
site_description: Next-generation DOM manipulation
site_author: RactiveJS contributors
site_url: https://ractive.js.org

repo_url: https://github.com/ractivejs/ractivejs.github.io
edit_uri: edit/dev/docs/

copyright: Â©RactiveJS contributors. Ractive.js is a free and open source project released under the MIT license.

theme_dir: theme


extra_css:
  - /static/css/index.css
extra_javascript:
  - static/js/index.js

extra:
  lib_url: https://github.com/ractivejs/ractive
  favicon: /static/img/favicon.ico
  theme_color: "#729D34"

pages:
  - Ractive.js: index.md
  - Get Started:
    - Hello, world!: get-started/tutorials/hello-world.md
    - Nested Properties: get-started/tutorials/nested-properties.md
    - Expressions: get-started/tutorials/expressions.md
    - Events: get-started/tutorials/events.md
    - Conditional Sections: get-started/tutorials/conditional-sections.md
    - Iterative Sections: get-started/tutorials/iterative-sections.md
    - Two-way Binding: get-started/tutorials/two-way-binding.md
    - Partials: get-started/tutorials/partials.md
    - Triples (Embedded HTML): get-started/tutorials/triples-embedded-html.md
    - Components: get-started/tutorials/components.md
    - Animations: get-started/tutorials/animation.md
    - SVG: get-started/tutorials/svg.md
    - Transitions: get-started/tutorials/transitions.md
    - Decorators: get-started/tutorials/decorators.md
    - Support: get-started/support.md
    - Migrating: get-started/migrating.md
  - API:
    - Initialization Options: api/initialization-options.md
    - Static Properties: api/static-properties.md
    - Static Methods: api/static-methods.md
    - Instance Properties: api/instance-properties.md
    - Instance Methods: api/instance-methods.md
    - Context Object: api/context-object.md
    - Parse Object: api/parse-object.md
    - Transition Object: api/transition-object.md
    - Directives: api/directives.md
    - References: api/references.md
  - Extend:
    - Adaptors: extend/adaptors.md
    - Components: extend/components.md
    - Decorators: extend/decorators.md
    - Easings: extend/easings.md
    - Events: extend/events.md
    - Interpolators: extend/interpolators.md
    - Partials: extend/partials.md
    - Transitions: extend/transitions.md
  - Integrations:
    - Component Files: api/component-files.md
    - Loaders: integrations/loaders.md
    - Plugins: integrations/plugins.md
    - Tools: integrations/tools.md
    - Libraries: integrations/libraries.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Data Management: concepts/data-management.md
    - Event Management: concepts/event-management.md
    - Templates: concepts/templates.md
    - Rendering: concepts/rendering.md
    - Security: concepts/security.md
