site_name: Ractive.js
site_description: Next-generation DOM manipulation
site_author: RactiveJS contributors
site_url: https://ractive.js.org

repo_url: https://github.com/ractivejs/ractivejs.github.io
edit_uri: edit/dev/docs/

copyright: Â©RactiveJS contributors. Ractive.js is a free and open source project released under the MIT license.

theme_dir: theme


extra_css:
  - /static/css/index.css
extra_javascript:
  - static/js/index.js

extra:
  lib_url: https://github.com/ractivejs/ractive
  favicon: /static/img/favicon.png
  theme_color: "#00818a"

markdown_extensions:
    - toc:
        anchorlink: true

pages:
  - Home: index.md
  - Get Started:
    - Hello, world!: tutorials/hello-world.md
    - Nested Properties: tutorials/nested-properties.md
    - Expressions: tutorials/expressions.md
    - Events: tutorials/events.md
    - Conditional Sections: tutorials/conditional-sections.md
    - Iterative Sections: tutorials/iterative-sections.md
    - Two-way Binding: tutorials/two-way-binding.md
    - Partials: tutorials/partials.md
    - Triples (Embedded HTML): tutorials/triples-embedded-html.md
    - Components: tutorials/components.md
    - Animations: tutorials/animation.md
    - SVG: tutorials/svg.md
    - Transitions: tutorials/transitions.md
    - Decorators: tutorials/decorators.md
  - API: api.md
  - Plugins: plugins.md
  - Resources: resources.md
  - Concepts: concepts.md
  - Support: support.md
  - Legacy:
    - '0.9':
      - API: legacy/0.9/api.md
      - Plugins: legacy/0.9/plugins.md
      - Concepts: legacy/0.9/concepts.md
