site_name: Ractive.js

site_url: https://ractive.js.org
repo_url: https://github.com/ractivejs/ractive

site_description: Next-generation DOM manipulation

site_author: RactiveJS contributors
copyright: Â©RactiveJS contributors. Ractive.js is a free and open source project released under the MIT license.

theme: cinder
extra_css:
  - css/index.css
extra_javascript:
  - js/index.js

pages:
  - Get Started:
    - Introduction: index.md
    - 60-second Setup: get-started/60-second-setup.md
    - Examples:
      - Analog Clock: get-started/examples/analog-clock.md
      - Animated Chart: get-started/examples/animated-chart.md
      - Comments: get-started/examples/comments.md
      - Donut Chart: get-started/examples/donut-chart.md
      - Illustration: get-started/examples/illustration.md
      - Rating Sars: get-started/examples/rating-stars.md
      - ToDo List: get-started/examples/todo-list.md
    - Debugging: get-started/debugging.md
    - Support: get-started/support.md
    - Contributing: get-started/contributing.md
  - API:
    - Initialization Options: api/initialization-options.md
    - Static Properties: api/static-properties.md
    - Static Methods: api/static-methods.md
    - Instance Properties: api/instance-properties.md
    - Instance Methods: api/instance-methods.md
    - Helper Objects:
      - Node Info: api/helper-objects/node-info.md
      - Parse: api/helper-objects/parse.md
      - Transition: api/helper-objects/transition.md
    - Errors: api/errors.md
  - Integrations:
    - Loaders: integrations/loaders.md
    - Plugins: integrations/plugins.md
    - Tools: integrations/tools.md
    - Libraries: integrations/libraries.md
  - Extend:
    - Adaptors: extend/adaptors.md
    - Components: extend/components.md
    - Decorators: extend/decorators.md
    - Easings: extend/easings.md
    - Events: extend/events.md
    - Interpolators: extend/interpolators.md
    - Partials: extend/partials.md
    - Transitions: extend/transitions.md
  - Concepts:
    - Architecture:
      - Overview: concepts/architecture/overview.md
      - Parser: concepts/architecture/parser.md
      - Model: concepts/architecture/model.md
      - View: concepts/architecture/view.md
    - Data Binding:
      - Array Modification: concepts/data-binding/array-modification.md
      - Computed Properties: concepts/data-binding/computed-properties.md
      - Dependents: concepts/data-binding/dependents.md
      - Magic Mode: concepts/data-binding/magic-mode.md
      - Observers: concepts/data-binding/observers.md
      - Parallel DOM: concepts/data-binding/parallel-dom.md
      - Two-Way Binding: concepts/data-binding/two-way-binding.md
    - Events:
      - Overview: concepts/events/overview.md
      - Bubbling: concepts/events/bubbling.md
      - Directives: concepts/events/directives.md
      - Method Calls: concepts/events/method-calls.md
      - Proxy Events: concepts/events/proxy-events.md
      - Publish-Subscribe: concepts/events/publish-subscribe.md
    - Rendering:
      - Progressive Enhancement: concepts/rendering/progressive-enhancement.md
      - Server-Side Rendering: concepts/rendering/server-side-rendering.md
    - Security:
      - CSP: concepts/security/csp.md
    - Templates:
      - Overview: concepts/templates/overview.md
      - Elements: concepts/templates/elements.md
      - Expressions: concepts/templates/expressions.md
      - Keypaths: concepts/templates/keypaths.md
      - Mustaches: concepts/templates/mustaches.md
      - Parsing: concepts/templates/parsing.md
      - Pre-Parsing: concepts/templates/pre-parsing.md
      - References: concepts/templates/references.md
    - Authoring:
      - Component Files: concepts/authoring/component-files.md
  - Articles:
    - Introducing Ractive.js: articles/introducing-ractive-js.md
    - The Origins Of Ractive: articles/the-origins-of-ractive.md
    - Ractive.js Expressions And The New Wave Of Reactive Programming: articles/ractive-js-expressions-and-the-new-wave-of-reactive-programming.md
    - Ractive.js vs Angular: articles/ractive-vs-angular.md
    - Ractive.js vs React: articles/ractive-vs-react.md
