site_name: Ractive.js

site_url: https://ractive.js.org
repo_url: https://github.com/ractivejs/ractive

site_description: Next-generation DOM manipulation

site_author: RactiveJS contributors
copyright: Â©RactiveJS contributors. Ractive.js is a free and open source project released under the MIT license.

theme: cinder
theme_dir: custom_theme
extra_css:
  - css/index.css
extra_javascript:
  - js/index.js

pages:
  - Ractive.js: index.md
  - Get Started:
    - Hello, world!: get-started/tutorials/hello-world.md
    - Nested Properties: get-started/tutorials/nested-properties.md
    - Expressions: get-started/tutorials/expressions.md
    - Events: get-started/tutorials/events.md
    - Conditional Sections: get-started/tutorials/conditional-sections.md
    - Iterative Sections: get-started/tutorials/iterative-sections.md
    - Two-way Binding: get-started/tutorials/two-way-binding.md
    - Partials: get-started/tutorials/partials.md
    - Triples (Embedded HTML): get-started/tutorials/triples-embedded-html.md
    - Components: get-started/tutorials/components.md
    - Animations: get-started/tutorials/animation.md
    - SVG: get-started/tutorials/svg.md
    - Transitions: get-started/tutorials/transitions.md
    - Decorators: get-started/tutorials/decorators.md
    - Support: get-started/support.md
  - API:
    - Initialization Options: api/initialization-options.md
    - Static Properties: api/static-properties.md
    - Static Methods: api/static-methods.md
    - Instance Properties: api/instance-properties.md
    - Instance Methods: api/instance-methods.md
    - Attributes: api/attributes.md
    - Keypath Prefixes: api/keypath-prefixes.md
    - Special References: api/special-references.md
    - Context Object: api/context.md
    - Parse: api/parse.md
    - Transition: api/transition.md
  - Extend:
    - Adaptors: extend/adaptors.md
    - Components: extend/components.md
    - Decorators: extend/decorators.md
    - Easings: extend/easings.md
    - Events: extend/events.md
    - Interpolators: extend/interpolators.md
    - Partials: extend/partials.md
    - Transitions: extend/transitions.md
  - Integrations:
    - Component Files: api/component-files.md
    - Loaders: integrations/loaders.md
    - Plugins: integrations/plugins.md
    - Tools: integrations/tools.md
    - Libraries: integrations/libraries.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Rendering: concepts/rendering.md
    - Security: concepts/security.md
    - Data Binding: concepts/data-binding.md
    - Events: concepts/events.md
    - Templates: concepts/templates.md
