site_name: Ractive.js
site_description: Next-generation DOM manipulation
site_author: RactiveJS contributors
site_url: https://ractive.js.org

repo_url: https://github.com/ractivejs/ractivejs.github.io
edit_uri: edit/dev/docs/

copyright: Â©RactiveJS contributors. Ractive.js is a free and open source project released under the MIT license.

theme_dir: theme


extra_css:
  - /static/css/index.css
extra_javascript:
  - static/js/index.js

extra:
  lib_url: https://github.com/ractivejs/ractive
  favicon: /static/img/favicon.ico
  theme_color: "#729D34"

markdown_extensions:
    - toc:
        anchorlink: true

pages:
  - Ractive.js: index.md
  - Get Started:
    - Hello, world!: tutorials/hello-world.md
    - Nested Properties: tutorials/nested-properties.md
    - Expressions: tutorials/expressions.md
    - Events: tutorials/events.md
    - Conditional Sections: tutorials/conditional-sections.md
    - Iterative Sections: tutorials/iterative-sections.md
    - Two-way Binding: tutorials/two-way-binding.md
    - Partials: tutorials/partials.md
    - Triples (Embedded HTML): tutorials/triples-embedded-html.md
    - Components: tutorials/components.md
    - Animations: tutorials/animation.md
    - SVG: tutorials/svg.md
    - Transitions: tutorials/transitions.md
    - Decorators: tutorials/decorators.md
  - API: api.md
  - Plugins: plugins.md
  - Integrations: integrations.md
  - Concepts: concepts.md
  - Workflows: workflows.md
  - Support: support.md
